### ISSUE TITLE
Crash in destructuring assignment with splats

### ISSUE THREAD

**Issue by bazineta** [pwlmaciejewski/coffeelint-variable-scope#4]
I'm seeing a crash here:

https://github.com/pwlmaciejewski/coffeelint-variable-scope/blob/master/index.js#L113

When parsing statements of the format:

[foo, bar...] = baz.split ' '

The issue is with 'bar'; in such cases, v.base is undefined.

**Comment by pwlmaciejewski** [comment]
@bazineta Thanks! Could you check if changes on `dev` branch fix the problem for you?

**Comment by bazineta** [comment]
Resolves the issue, thanks!

**Comment by bchociej** [comment]
I think my issue #11 (which is in apparent dupe of this) is happening because the index.js file is not compiled from the latest index.coffee, at least in npm version 0.0.3. Try npm installing 0.0.3 and see what I mean.
